// Mock for jose module
module.exports = {
  compactDecrypt: jest.fn(),
  compactVerify: jest.fn(),
  compactSign: jest.fn(),
  compactEncrypt: jest.fn(),
  jwtVerify: jest.fn(),
  jwtSign: jest.fn(),
  jwtDecrypt: jest.fn(),
  jwtEncrypt: jest.fn(),
  generateSecret: jest.fn(),
  generateKeyPair: jest.fn(),
  importPKCS8: jest.fn(),
  importSPKI: jest.fn(),
  importX509: jest.fn(),
  exportPKCS8: jest.fn(),
  exportSPKI: jest.fn(),
  exportJWK: jest.fn(),
  importJWK: jest.fn(),
  decodeJwt: jest.fn(),
  decodeProtectedHeader: jest.fn(),
  decodeJws: jest.fn(),
  decodeJwe: jest.fn(),
  decodeJwt: jest.fn(),
  decodeProtectedHeader: jest.fn(),
  decodeJws: jest.fn(),
  decodeJwe: jest.fn(),
};
